### ISSUE TITLE
NPE in 3.18 NRProcessorWrapper::process

### ISSUE THREAD

**Issue by kbudaeus** [newrelic-experimental/newrelic-java-camel#7]
Hello NewRelic Camel team, 

With spring-boot-start-parent 2.7.5 and camel version 3.18.3
and extracting the instrumentation-tar to $NEW_RELIC_HOME/extensions
I get the following stacktrace.
`
[2022-11-14 18:04:30,673] [Camel (camel-1) thread #3 - jpakpbt://ch.voev.koserv.kontrolldatenexport.etcd.model.kontrollprotokolle.KontrollprotokollBarcode] WARN  org.apache.camel.component.jpa.JpaConsumer run - Error processing last message due: java.lang.NullPointerException. Will commit all previous successful processed message, and ignore this last failure.
javax.persistence.PersistenceException: java.lang.NullPointerException
	at org.apache.camel.component.jpa.JpaConsumer$1.run(JpaConsumer.java:135)
	at org.apache.camel.component.jpa.DefaultTransactionStrategy$1.doInTransaction(DefaultTransactionStrategy.java:48)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140)
	at org.apache.camel.component.jpa.DefaultTransactionStrategy.executeInTransaction(DefaultTransactionStrategy.java:46)
	at org.apache.camel.component.jpa.JpaConsumer.poll(JpaConsumer.java:104)
	at org.apache.camel.support.ScheduledPollConsumer.doRun(ScheduledPollConsumer.java:202)
	at org.apache.camel.support.ScheduledPollConsumer.run(ScheduledPollConsumer.java:116)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.NullPointerException: null
	at com.newrelic.agent.tracers.AbstractTracer.shouldAddAttribute(AbstractTracer.java:345)
	at com.newrelic.agent.tracers.AbstractTracer.setAttribute(AbstractTracer.java:349)
	at com.newrelic.agent.tracers.AbstractTracer.setAttributeIfValid(AbstractTracer.java:340)
	at com.newrelic.agent.tracers.AbstractTracer.addCustomAttributes(AbstractTracer.java:332)
	at com.nr.instrumentation.apache.camel.NRProcessorWrapper.process(NRProcessorWrapper.java:35)
	at org.apache.camel.component.jpa.JpaConsumer.processBatch(JpaConsumer.java:201)
	at org.apache.camel.component.jpa.JpaConsumer$1.run(JpaConsumer.java:130)
	... 12 common frames omitted
`

Processing the route.

**Comment by dhilpipre** [comment]
fixed in new release (2.1)
